apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shieldops.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shieldops.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{- if eq $key "SHIELDOPS_OPA_ENDPOINT" }}
  {{ $key }}: {{ include "shieldops.opaEndpoint" $ | quote }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
