{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "shieldops.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shieldops.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "shieldops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
---
{{- if .Values.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "shieldops.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shieldops.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "shieldops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
{{- end }}
