apiVersion: v1
kind: Service
metadata:
  name: {{ include "shieldops.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shieldops.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "shieldops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
---
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shieldops.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shieldops.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "shieldops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
{{- end }}
