apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shieldops-ingress
  namespace: shieldops
  labels:
    app: shieldops
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.shieldops.io
        - dashboard.shieldops.io
      secretName: shieldops-tls
  rules:
    - host: api.shieldops.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shieldops-api
                port:
                  number: 80
    - host: dashboard.shieldops.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shieldops-dashboard
                port:
                  number: 80
